server:
  port: 9021

spring:
  dubbo:
    application:
      name: dubbo-consumer
      registry: zookeeper://192.168.3.199:2181

  #rabbitMQ 参数配置
  rabbitmq:
    host: 192.168.3.199
    port: 5672
    username: admin
    password: 123456