server:
  port: 9021

spring:
  dubbo:
    application:
      name: dubbo-consumer
      registry: zookeeper://127.0.0.1:2181

  #rabbitMQ 参数配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest